/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.boyarsky.dapos;

import jetbrains.exodus.env.Environment;
import jetbrains.exodus.env.Environments;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.IOException;
import java.nio.file.Paths;

@Configuration
public class App {
    public static final String appName = "dapos";
    public static final String appDir = "." + appName;
    public static final String appDataDir = appDir + "/app-data";
    public static final String appDbDir = appDir + "/app-db";
    public static final String appKeystore = appDir + "/app-keystore";

    @Bean
    public Environment env() throws IOException, InterruptedException {
        return Environments.newInstance(Paths.get(System.getProperty("user.home")).resolve(appDbDir).toAbsolutePath().toString());
    }
}
