/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.boyarsky.dapos;

import jetbrains.exodus.entitystore.PersistentEntityStore;
import jetbrains.exodus.entitystore.PersistentEntityStores;
import jetbrains.exodus.env.Environment;
import jetbrains.exodus.env.Environments;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

@Configuration
public class DbConfig {

    Path dbPath;

    @Autowired
    @Qualifier("dbDir")
    public void setDbPath(Path dbPath) {
        this.dbPath = dbPath;
    }

    @Bean
    public Environment env() throws IOException, InterruptedException {
        return Environments.newInstance(dbPath.toAbsolutePath().toString());
    }

    @Bean
    public PersistentEntityStore store() throws IOException, InterruptedException {
        return PersistentEntityStores.newInstance(env(), "MAIN");
    }
}
