/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.boyarsky.dapos.config;

import jetbrains.exodus.entitystore.PersistentEntityStore;
import jetbrains.exodus.entitystore.PersistentEntityStoreImpl;
import jetbrains.exodus.entitystore.PersistentEntityStores;
import jetbrains.exodus.env.Environment;
import jetbrains.exodus.env.Environments;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.IOException;
import java.nio.file.Path;

@Configuration
public class DbConfig {

    Path dbPath;

    @Autowired
    @Qualifier("dbDir")
    public void setDbPath(Path dbPath) {
        this.dbPath = dbPath;
    }

    @Bean // default destroy method (close)
    public Environment env() throws IOException, InterruptedException {
        return Environments.newInstance(dbPath.toAbsolutePath().toString());
    }

    @Bean // destroy method is registered by default (close() method)
    public PersistentEntityStore store() throws IOException, InterruptedException {
        PersistentEntityStoreImpl store = PersistentEntityStores.newInstance(env(), "MAIN");
//        store.executeInExclusiveTransaction(txn -> {
//            store.registerCustomPropertyType(txn, ComparableByteArray.class, new ComparableByteArrayBinding());
//        });
        return store;
    }
}
